name: Android CI/CD

on:
  push:
    branches:
      - main

env:
  ANDROID_SDK_ROOT: /opt/android-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '16'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

    - name: Cache Gradle wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: 31.0.0

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Run Unit Tests
      run: ./gradlew testDebug

    - name: Run Espresso Tests
      run: ./gradlew connectedDebugAndroidTest

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
